spring.application.name=kv-store
server.port=8080
node.id=node-1
node.self=${NODE_SELF:http://localhost:8080}
cluster.nodes=${CLUSTER_NODES:http://localhost:8080}
cluster.virtual-nodes=16
cluster.replication-factor=1
consistency.w=1
consistency.r=1