spring.application.name=kv-store
server.port=8080
node.id=node-1
node.self=http://localhost:8080
cluster.nodes=http://localhost:8080,http://localhost:8081,http://localhost:8082
cluster.virtual-nodes=16
cluster.replication-factor=2
consistency.w=2
consistency.r=1